# Generated by Django 6.0 on 2026-01-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_iks',
            field=models.BooleanField(default=False),
        ),
    ]
