# Generated by Django 6.0 on 2026-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inquiry_is_iks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='is_iks',
        ),
    ]
