# Generated by Django 6.0 on 2026-01-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_technicalstaffs_delete_technicalstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='technical_staff/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('students', models.PositiveIntegerField(default=0)),
                ('courses', models.PositiveIntegerField(default=0)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TechnicalStaffs',
        ),
    ]
