# Generated by Django 6.0 on 2026-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_technicalstaff_delete_technicalstaffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='e.g., MBA Student, Data Scientist', max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('testimonial_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='Rating out of 5', max_digits=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-is_featured', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.AddField(
            model_name='instructor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text='e.g., Web Development, Data Science', max_length=200),
        ),
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.CharField(blank=True, default='', help_text='e.g., Professor, Dr., etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='total_students',
            field=models.IntegerField(default=0, help_text='Total students taught'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='years_experience',
            field=models.IntegerField(default=0, help_text='Years of teaching experience'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
