# Generated by Django 6.0 on 2026-01-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testimonial_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_international',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
