# Generated by Django 6.0 on 2026-01-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testimonial_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
