# Generated by Django 6.0 on 2026-01-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_inquiry_is_email_verified_inquiry_is_mobile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='is_mobile_verified',
        ),
    ]
