# Generated by Django 6.0 on 2026-01-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_price_international'),
        ('main', '0010_remove_inquiry_is_mobile_verified'),
    ]

    operations = [
    ]
