# Generated by Django 6.0 on 2026-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='IKSRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iks_course', models.CharField(choices=[('IKS_1', 'IKS_1 (Sem1)'), ('IKS_3', 'IKS_3 (Sem3)')], max_length=20)),
                ('admission_year', models.CharField(max_length=4)),
                ('programme', models.CharField(max_length=100)),
                ('college_department', models.CharField(max_length=200)),
                ('gcas_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gcas_conf_no', models.CharField(blank=True, max_length=50, null=True)),
                ('abc_number', models.CharField(max_length=50)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('medium', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Other', 'Other')], max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('category', models.CharField(choices=[('Open/Gen', 'Open/Gen'), ('EWS', 'EWS'), ('OBC/SEBC', 'OBC/SEBC'), ('ST', 'ST'), ('SC', 'SC')], max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
